[tool]
id          = "com.tyshi00.games"
label       = "Games"
versionCode = 2
versionName = "0.2.0"
permissions = []                              # everything runs fully on-device, no permissions needed
# change if you run this on an LP3!
# serverPackage = "com.lightos"
serverPackage = "com.thelightphone.sdk.emulator"
